"""initial schema

Revision ID: 03246cebe338
Revises: 
Create Date: 2026-09-06 18:09:11.844997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03246cebe338'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Required for the EXCLUDE constraint on bookings: GiST needs btree_gist
    # to support the '=' operator on an integer column (connector_id).
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_operators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_name', sa.String(length=100), nullable=False),
    sa.Column('contact_email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','suspended','closed')", name='ck_operators_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_email')
    )
    op.create_table('connector_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_name', sa.String(length=30), nullable=False),
    sa.Column('standard_max_power_kw', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_name')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address_line', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('registration_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('account_status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("account_status IN ('active','suspended','closed')", name='ck_users_account_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicle_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('battery_capacity_kwh', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make', 'model_name', name='uq_vehicle_models_make_model')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), server_default='station_manager', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("role IN ('super_admin','station_manager','finance_manager')", name='ck_admins_role'),
    sa.CheckConstraint("status IN ('active','suspended')", name='ck_admins_status'),
    sa.ForeignKeyConstraint(['operator_id'], ['charging_operators.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('charging_stations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','under_maintenance')", name='ck_stations_status'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['operator_id'], ['charging_operators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_connector_types',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('connector_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connector_type_id'], ['connector_types.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['vehicle_models.id'], ),
    sa.PrimaryKeyConstraint('model_id', 'connector_type_id')
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('vehicle_status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("vehicle_status IN ('active','inactive')", name='ck_vehicles_status'),
    sa.ForeignKeyConstraint(['model_id'], ['vehicle_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_table('chargers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('charger_model', sa.String(length=50), nullable=True),
    sa.Column('power_capacity_kw', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive','under_maintenance')", name='ck_chargers_status'),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_admins',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.PrimaryKeyConstraint('station_id', 'admin_id')
    )
    op.create_table('tariffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('price_per_kwh', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id')
    )
    op.create_table('connectors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('charger_id', sa.Integer(), nullable=False),
    sa.Column('connector_type_id', sa.Integer(), nullable=False),
    sa.Column('max_power_kw', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='available', nullable=False),
    sa.CheckConstraint("status IN ('available','occupied','reserved','out_of_service')", name='ck_connectors_status'),
    sa.ForeignKeyConstraint(['charger_id'], ['chargers.id'], ),
    sa.ForeignKeyConstraint(['connector_type_id'], ['connector_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('booking_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='confirmed', nullable=False),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    postgresql.ExcludeConstraint((sa.column('connector_id'), '='), (sa.text('tstzrange(start_time, end_time)'), '&&'), where=sa.text("status = 'confirmed'"), using='gist', name='ex_bookings_no_overlap'),
    sa.CheckConstraint("status IN ('confirmed','cancelled','completed','no_show')", name='ck_bookings_status'),
    sa.CheckConstraint('end_time > start_time', name='ck_bookings_time_order'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('charging_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_status', sa.String(length=20), server_default='initiated', nullable=False),
    sa.Column('energy_delivered_kwh', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.CheckConstraint("session_status IN ('initiated','charging','completed','interrupted','failed')", name='ck_sessions_status'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('booking_id')
    )
    op.create_table('bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('energy_charge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('generated_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['charging_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payment_method', sa.String(length=30), nullable=False),
    sa.Column('payment_status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('transaction_reference', sa.String(length=50), nullable=True),
    sa.CheckConstraint("payment_method IN ('card','upi','wallet','net_banking')", name='ck_payments_method'),
    sa.CheckConstraint("payment_status IN ('pending','successful','failed','refunded')", name='ck_payments_status'),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('bills')
    op.drop_table('charging_sessions')
    op.drop_table('bookings')
    op.drop_table('connectors')
    op.drop_table('tariffs')
    op.drop_table('station_admins')
    op.drop_table('chargers')
    op.drop_table('vehicles')
    op.drop_table('model_connector_types')
    op.drop_table('charging_stations')
    op.drop_table('admins')
    op.drop_table('vehicle_models')
    op.drop_table('users')
    op.drop_table('locations')
    op.drop_table('connector_types')
    op.drop_table('charging_operators')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS btree_gist")
