"""scope technicians to operator

Revision ID: 7746e19e72e9
Revises: d12930913237
Create Date: 2026-09-06 20:49:05.788271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7746e19e72e9'
down_revision: Union[str, Sequence[str], None] = 'd12930913237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('operator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'technicians', 'charging_operators', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technicians', type_='foreignkey')
    op.drop_column('technicians', 'operator_id')
    # ### end Alembic commands ###
