"""scope charging plans to operator

Revision ID: be67ed08af42
Revises: 7746e19e72e9
Create Date: 2026-09-06 21:21:00.454978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be67ed08af42'
down_revision: Union[str, Sequence[str], None] = '7746e19e72e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('charging_plans', sa.Column('operator_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('charging_plans_plan_name_key'), 'charging_plans', type_='unique')
    op.create_unique_constraint('uq_plans_operator_name', 'charging_plans', ['operator_id', 'plan_name'])
    op.create_foreign_key(None, 'charging_plans', 'charging_operators', ['operator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'charging_plans', type_='foreignkey')
    op.drop_constraint('uq_plans_operator_name', 'charging_plans', type_='unique')
    op.create_unique_constraint(op.f('charging_plans_plan_name_key'), 'charging_plans', ['plan_name'], postgresql_nulls_not_distinct=False)
    op.drop_column('charging_plans', 'operator_id')
    # ### end Alembic commands ###
