"""add v2 and advanced entities

Revision ID: d12930913237
Revises: 03246cebe338
Create Date: 2026-09-06 18:58:23.407081

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd12930913237'
down_revision: Union[str, Sequence[str], None] = '03246cebe338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charging_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_name', sa.String(length=50), nullable=False),
    sa.Column('subscription_fee', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('priority_booking', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('max_sessions', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.CheckConstraint("status IN ('active','inactive')", name='ck_plans_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('plan_name')
    )
    op.create_table('technicians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('specialization', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('sent_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("type IN ('Booking','Payment','Maintenance','Promotion','System')", name='ck_notifications_type'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('auto_renew', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("status IN ('active','expired','cancelled')", name='ck_subscriptions_status'),
    sa.ForeignKeyConstraint(['plan_id'], ['charging_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_affected', sa.String(length=50), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('station_operating_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('opening_time', sa.Time(), nullable=False),
    sa.Column('closing_time', sa.Time(), nullable=False),
    sa.CheckConstraint("day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')", name='ck_operating_hours_day'),
    sa.CheckConstraint('closing_time > opening_time', name='ck_operating_hours_time_order'),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'day_of_week', name='uq_operating_hours_station_day')
    )
    op.create_table('station_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=500), nullable=True),
    sa.Column('review_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_reviews_rating'),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'station_id', name='uq_review_user_station')
    )
    op.create_table('maintenance_tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('issue_description', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.String(length=10), server_default='medium', nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.CheckConstraint("priority IN ('low','medium','high','critical')", name='ck_maintenance_priority'),
    sa.CheckConstraint("status IN ('open','in_progress','completed','cancelled')", name='ck_maintenance_status'),
    sa.ForeignKeyConstraint(['connector_id'], ['connectors.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['charging_stations.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('meter_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('energy_reading_kwh', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('power_output_kw', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('voltage', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('current', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['charging_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('refund_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.CheckConstraint("status IN ('pending','approved','rejected')", name='ck_refunds_status'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id')
    )
    op.add_column('bills', sa.Column('subscription_discount', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False))
    op.add_column('payments', sa.Column('subscription_id', sa.Integer(), nullable=True))
    op.alter_column('payments', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint(None, 'payments', ['subscription_id'])
    op.create_foreign_key(None, 'payments', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###
    # Not autodetected on an existing table: the exclusive-or between bill_id/subscription_id.
    op.create_check_constraint(
        'ck_payments_exactly_one_target',
        'payments',
        "(bill_id IS NOT NULL AND subscription_id IS NULL) OR "
        "(bill_id IS NULL AND subscription_id IS NOT NULL)",
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_payments_exactly_one_target', 'payments', type_='check')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='unique')
    op.alter_column('payments', 'bill_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('payments', 'subscription_id')
    op.drop_column('bills', 'subscription_discount')
    op.drop_table('refunds')
    op.drop_table('meter_readings')
    op.drop_table('maintenance_tickets')
    op.drop_table('station_reviews')
    op.drop_table('station_operating_hours')
    op.drop_table('audit_logs')
    op.drop_table('subscriptions')
    op.drop_table('notifications')
    op.drop_table('technicians')
    op.drop_table('charging_plans')
    # ### end Alembic commands ###
